channels:
- conda-forge
- defaults
dependencies:
- asyncssh
- caiman >= 1.10.0
- cellpose
- dask
- distributed
- h5py
- hdf5storage
- mesmerize-core
- mslex
- nest-asyncio
- ipympl
- opencv
- optype-numpy
- pip
- pydantic
- pytorch
- setuptools < 82.0.0  # for mesmerize-viz (pkg_resources dependency in pygfx version)
- scipy-stubs
- typing_extensions
- pip:
  - mesmerize-viz
  - fastplotlib ~= 0.1.0.a17
  - suite2p
