# Info for pixi-build
[package.build.backend]
name = "pixi-build-python"
version = "0.4.*"

[package.build.config]
ignore-pypi-mapping = false

[package.host-dependencies]
uv = "*"  # added for faster installation

[package.run-dependencies]
# add in git dependencies manually since pypi-mapping ignores them
fastplotlib = { git = "ssh://git@github.com/ethanbb/fastplotlib", branch = "a16-numpy2"}
mesmerize-viz = { git = "ssh://git@github.com/proektlab/mesmerize-viz", branch = "master" }
# add in [notebook] dependencies of fastplotlib manually since conda-build doesn't handle them
jupyterlab = "*"
jupyter-rfb = ">=0.4.1"
ipywidgets = ">=8.0.0,<9"
sidecar = "*"
# add in [jupyter] dependencies of caiman
jupyter = "*"
jupyter_bokeh = "*"
pyqtgraph = "*"
tk = "*"
# add in [numpy] dependencies of optype
numpy-typing-compat = ">=20250818.1.25,<20251207"

[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[dependencies]
caiman = { path = "../CaImAn" }
mesmerize-core = { path = "../mesmerize-core" }
cmcode = { path = "." }
