[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cmcode"
version = "0.1.0"
description = "Caiman 2P analysis code for Proekt Lab"
requires-python = ">=3.10"
authors = [
    {name = "Ethan Blackwood", email = "ethanbblackwood@gmail.com"}
]
dependencies = [
    "asyncssh",
    "caiman[jupyter]>=1.10.0",
    "cellpose",
    "dask",
    "datashader",
    "fastplotlib[notebook] @ git+https://github.com/ethanbb/fastplotlib.git@a16-numpy2",
    "h5py",
    # "hdf5storage",  # required but commenting out for now until https://github.com/prefix-dev/pixi/issues/6452 is fixed
    "holoviews",
    "ipympl",
    "mesmerize-core",
    "mesmerize-viz @ git+https://github.com/proektlab/mesmerize-viz",
    "mslex",
    "nest-asyncio",
    "opencv-python",
    "optype[numpy]",
    "pydantic",
    "scipy-stubs",
    "suite2p @ git+https://github.com/proektlab/suite2p.git@proekt-dev",
    "tabulate",
    "torch",
    "typing_extensions"
]

[project.scripts]
caimanlab = "cmcode.remote.caimanlab:main"

[tool.setuptools.packages.find]
include = ["cmcode*"]


[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "basic"
