"""
Holds information about hosts that can be used for cluster processing

See private/example_local_environment.py for an example. 
"""
from copy import copy
from dataclasses import dataclass, field
from functools import cache
import os
import psutil
import shlex
from socket import gethostname
import sys
from types import ModuleType
from typing import Optional, Protocol, Union, runtime_checkable

import mslex

from cmcode.util.types import UnknownHostError, UnknownPartitionError


@dataclass
class PartitionInfo:
    """Info about resources available on a SLURM partition"""
    name: str
    cores_per_node: dict[str, int]  # mapping of node self-names to number of cores
    host: 'HostInfo'  # host that can be used to login to cluster

    @property
    def n_cores(self) -> int:
        """Total CPUs available"""
        return sum(self.cores_per_node.values())
    
    @property
    def max_cores_per_job(self) -> int:
        """max cores that can be allocated to a single job"""
        return min(self.cores_per_node.values())
    
    @property
    def nodes(self) -> list[str]:
        return list(self.cores_per_node.keys())
    
    def get_full_name(self, separator: str = '/') -> str:
        return f'{self.host.name}{separator}{self.name}'


@dataclass
class HostInfo:
    """Hold information about a host that may be used to do analysis remotely (or locally)"""
    name: str  # friendly name (lowercase)
    self_name: str  # should be the output of socket.gethostname()
    is_pc: bool
    n_cores: int  # number of cores that can be used locally
    envname: Optional[str]  # name of conda environment to use
    ssh_user: Optional[str] = None  # defaults to not specifying user (using current user)
    ssh_name: str = ''  # a name used to access host remotely
    partitions: dict[str, PartitionInfo] = field(default_factory=dict)  #  resources available on each SLURM partition
    default_partition: Optional[str] = None
    autogenerated: bool = False

    def __post_init__(self):
        if self.ssh_name == '':
            self.ssh_name = self.self_name

        if self.n_cores is None and self.partitions is None:
            raise ValueError('Must provide at least one of ncores or partitions')

    @property
    def host(self) -> 'HostInfo':
        return self

    @property
    def is_local(self) -> bool:
        return self.self_name == gethostname()
    
    @property
    def lex(self) -> ModuleType:
        """Which module to use for shell escaping/quoting"""
        return mslex if self.is_pc else shlex

    @property
    def iscluster(self) -> bool:
        """Whether SLURM can be used"""
        return len(self.partitions) > 0

    def get_full_name(self, separator: str = '/') -> str:
        return self.self_name
    

@runtime_checkable
class WorkerContext(Protocol):
    """Info about place where a parallel worker can be run, e.g. a host or SLURM partition"""
    def get_full_name(self, separator: str = '/') -> str:
        """Unique name to specify the context"""
        ...

    @property
    def n_cores(self) -> int:
        """Total CPUs available in the context"""
        ...

    @property
    def host(self) -> HostInfo:
        """The host where this context resides"""
        ...


@cache
def get_localhost_info() -> HostInfo:
    """
    Gather information about the local host
    """
    self_name = gethostname()

    n_cores = psutil.cpu_count()
    if n_cores is None:
        raise RuntimeError('Could not determine number of cores')

    return HostInfo(
        name=self_name.lower(),
        self_name=self_name,
        is_pc=sys.platform == 'win32',
        envname=os.environ.get('CONDA_DEFAULT_ENV', None),
        n_cores=n_cores,
        autogenerated=True
    )


class NetworkInfo:
    """Holds information about all hosts/partitions on a network."""

    def __init__(self, *known_hosts: HostInfo):
        """Make a NetworkInfo object, optionally initialized with some existing objects"""
        self.hosts = {host.name: host for host in known_hosts}
    
    def add_host(self, overwrite: bool = False, **host_args):
        host_info = HostInfo(**host_args)
        if host_info.name in self.hosts and not overwrite:
            return
        self.hosts[host_info.name] = host_info

    def add_host_alias(self, base_host: Union[str, HostInfo], name: str, **override_args):
        """Add a shallow copy with some modified parameters (so partition info is synchronized)"""
        if not isinstance(base_host, HostInfo):
            base_host_info = self.get_host(base_host)
            if base_host_info is None:
                raise UnknownHostError(base_host)
            base_host = base_host_info

        new_host_info = copy(base_host)
        new_host_info.name = name
        for param, val in override_args.items():
            setattr(new_host_info, param, val)
        self.hosts[name] = new_host_info

    def add_partition(self, parent_host: str, name: str, cores_per_node: dict[str, int],
                      set_default: bool = False):
        parent_host_info = self.get_host(parent_host)
        if parent_host_info is None:
            raise UnknownHostError(parent_host)
        partition_info = PartitionInfo(name=name, cores_per_node=cores_per_node,
                                       host=parent_host_info)
        if parent_host_info.partitions is None:
            parent_host_info.partitions = {}
        parent_host_info.partitions[name] = partition_info
        if set_default:
            parent_host_info.default_partition = name

    def get_host(self, host_name: str) -> Optional[HostInfo]:
        return self.hosts.get(host_name.lower())

    def find_localhost(self, name: Optional[str] = None) -> Optional[HostInfo]:
        """
        Try to find an existing entry that matches the current host
        If name is provided, tries to use this host first, if it exists.
        """
        self_name = gethostname()
        if name is not None and (host := self.get_host(name)):
            if host.self_name != self_name:
                raise ValueError('Name provided, but self_name for this entry conflicts with the result of gethostname')
            return host
    
        # try finding based on self_name
        for host in self.hosts.values():
            if host.self_name == self_name:
                return host
        
        return None

    def add_localhost(self, name: Optional[str] = None):
        """
        Add a 'localhost' entry, which is either an alias to an existing entry (if self_name matches)
        or a new entry. If adding a new entry, also adds an alias with the local hostname, or alias if provided.
        """
        # try adding alias
        found_host = self.find_localhost(name=name)
        if found_host is not None:
            self.add_host_alias(base_host=found_host, name='localhost')
        else:
            # add new host
            localhost = get_localhost_info()
            self.hosts[localhost.name] = localhost
            self.add_host_alias(base_host=localhost, name='localhost')

    def get_localhost(self) -> HostInfo:
        """Get localhost info, adding an auto-generated entry if necessary"""
        if 'localhost' not in self.hosts:
            self.add_localhost()
        return self.hosts['localhost']

    
    def get(self, full_name: str, prefer_default_partition: bool = False) -> WorkerContext:
        """
        Resolve the name of a host or partition (in the format "host/partition")
        If prefer_default_partition is true, uses a default partition if there is one rather than the host
        when no partition is specified.
        """
        parts = full_name.split('/')
        host = parts[0]
        host_info = self.get_host(host)
        if host_info is None:
            raise UnknownHostError(host)
        
        if len(parts) == 1:
            if prefer_default_partition and host_info.default_partition is not None:
                partition = host_info.default_partition
            else:
                return host_info
        else:
            # resolve partition
            partition = parts[1]

        part_info = host_info.partitions.get(partition)
        if part_info is None:
            raise UnknownPartitionError(host, partition)
        return part_info

def get_cpu_limits(network: NetworkInfo, hostname: str, partition: Optional[str] = None) -> tuple[int, int]:
    """For given host and SLURM partition if given, return the total CPUs and max usable per job"""
    host_info = network.get_host(hostname)
    if host_info is None:
        raise RuntimeError(f'Hostname ({hostname}) not found - cannot start SLURM jobs')

    if partition is None and host_info.default_partition is not None:
        partition = host_info.default_partition

    if partition is not None:
        if partition not in host_info.partitions:
            raise RuntimeError(f'Cannot find info about partition {partition} on host {hostname}')
        partition_info = host_info.partitions[partition]
        cpus_available = partition_info.n_cores
        max_cpus_per_job = partition_info.max_cores_per_job
    else:
        cpus_available = host_info.n_cores
        max_cpus_per_job = cpus_available

    return cpus_available, max_cpus_per_job


# Global variables, getters and setters
_network_hosts: NetworkInfo = NetworkInfo()

def set_network_hosts(network: NetworkInfo):
    global _network_hosts
    _network_hosts = network

def get_network_hosts() -> NetworkInfo:
    return _network_hosts